---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-v17
spec:
  # https://github.com/cloudnative-pg/cloudnative-pg/issues/2570
  enablePDB: false
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  instances: 2
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_connections: "300"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      shared_buffers: 512MB
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      memory: "4Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  storage:
    size: 20Gi
    storageClass: ceph-block
  superuserSecret:
    name: cloudnative-pg-secret

  backup:
    barmanObjectStore:
      destinationPath: "s3://cloudnativepg-app-backups"
      endpointURL: "https://542984caaa7dbec621de30100e1e7b23.r2.cloudflarestorage.com"
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: backupAccessKeyId
        secretAccessKey:
          name: cloudnative-pg-secret
          key: backupAccessSecret
      wal:
        compression: gzip
      data:
        compression: gzip
