---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: home-ops
  namespace: database
spec:
  configuration:
    data:
      compression: bzip2
      jobs: 4
    destinationPath: s3://cnpg-home-ops/
    endpointURL: "https://542984caaa7dbec621de30100e1e7b23.r2.cloudflarestorage.com"
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: backupAccessKeyId
      secretAccessKey:
        name: cloudnative-pg-secret
        key: backupAccessSecret
    wal:
      compression: bzip2
      maxParallel: 4
  retentionPolicy: 30d
