---
apiVersion: v1
kind: Service
metadata:
  name: postgres-home-ops
  annotations:
    lbipam.cilium.io/ips: "10.0.30.43"
spec:
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: home-ops
    cnpg.io/instanceRole: primary
  type: LoadBalancer
