---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./external-secrets/ks.yaml
  - ./intel-device-plugin/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./spegel/ks.yaml
  - ./system-upgrade-controller/ks.yaml
