---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tasmobackup
  namespace: default
spec:
  sourcePVC: data-tasmobackup-0
  trigger:
    schedule: "0 4 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: tasmobackup-restic-secret
    cacheCapacity: 5Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
