---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates.yaml
  - helmrelease.yaml
  - ocirepository.yaml
  - podmonitor.yaml
commonLabels:
  app.kubernetes.io/name: teleport
  app.kubernetes.io/instance: teleport
