---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: discord-alert
  namespace: flux-system
spec:
  summary: "Cluster Flux"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  exclusionList:
    #- "^Dependencies.*"
    - "^Namespace/flux-system configured.*"
