apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: flux-system
stringData:
    admin_password: ENC[AES256_GCM,data:Qdui1BtYR4WdI4ErH28=,iv:dnlSfPtTJccjXCaQVu43yFUxbv3802nau7MkseUB0M8=,tag:HzQnz3b1n/Uf1dLiiGVPSA==,type:str]
    user_1_username: ENC[AES256_GCM,data:AWUjnUQewAggF/d10g==,iv:SiLuaVKYnscX00cS6ETJKNCeEc5oAhjBXnR84iNSuLU=,tag:S1B/dV0cj0fKqRMuFXimBg==,type:str]
    user_1_password: ENC[AES256_GCM,data:3tIoMemn++lsO0cM,iv:HrX3lAwuTpLFW0qQwRiy6P3je5mpqjLrh6JXbBp02WE=,tag:FOYhN6zd7p8XmEa03hZp8g==,type:str]
    user_2_username: ENC[AES256_GCM,data:ZyQKSU0SE4wq,iv:Cr9iMESdZhJltWJ3awaj9TIA4/pI9CY5E5CcGSFGBSg=,tag:mmEGhNESt1KPjD8wgiHNrg==,type:str]
    user_2_password: ENC[AES256_GCM,data:4rw2BjLFIDd+8A+8,iv:FGteZtJp4uuZoc9RaBrbtuyyMRteCH4Yy1W+pKhAZes=,tag:P7L5p5N9n7U+WJrwuYy1WQ==,type:str]
    user_3_username: ENC[AES256_GCM,data:1OoGy/5JQw==,iv:g7nqXiUAm533SBsOvUeheq3vGaDfPZ8JNl2zgHTLYC0=,tag:3CY8WJtkabMeZ8zALia9Zg==,type:str]
    user_3_password: ENC[AES256_GCM,data:4IpWMEBPOd8qjYAX,iv:uj0Qjh+1Ng/XNKu1z4+wovFM+IMMrRVGMlghuO2Mqy8=,tag:QUfn42WLo6oT03oXTxtqoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbk94SkJUdzF5Unk5dXRw
            UUJ0eU1TTm1OWTJsVUJmTFFjR3N5Vm10dVQwClpKN0NQbTlwdEl3SUdjSHExYzY2
            V0E2QjNFb01MN2o4Q1pjYTRHTU9KS2MKLS0tIGRpek5hdDEzaUNySnZxcktPMXRF
            ZlpRVmhZTmNCMUZxekx3dFp5eCs2bDgKLOKAwcQxJI3esUFsXR1ws86gRGW0dg8P
            LATjwpCFhA7tN2MIDEqJGS7uxuq4zdUmjleB7NNtNOE0cOLkB8K4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-17T01:11:08Z"
    mac: ENC[AES256_GCM,data:zxQmRqA2OVh4h0rMbtrOTVIg7tB/5rNu8Zu+K9Q83ya7xi80Rdr2XNgWx08ESNGzntjlhIoBCUOj1ORcdQ8VAl1+hMzINjHoWAR4aIn6vjrUtUu/JgoGzZO4d3wVvS2AuFlHDChxG3ldaRA9pENgSFNi8Co7Ws8uBhxusNQR/Rc=,iv:cGRaBNYoFGWBEzAg0gOKQ6AnHfdZs50wNijew66deOc=,tag:lI8p8TerUqSUIxIJ7Z7/KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
