# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-restic-secret
    namespace: downloaders
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:nMHU8Nz3ab7VVv2kVveT0EUs1klwEixmjZHrXuKYGVRJtB9hWeubwvCCaiHz5DABxKb1cI9Jr+z8dZ9cCBaWQK3Y,iv:Nv6wy6NV3c4W8H/LLxH9eEHOKzwQPifm/Bdq2IYQ+1Q=,tag:EaOsBD18tURvreJTvqR6NA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/G00+iTN4pudbNIjWNyvfm7lQvl+ELx4u6bZlwr989+h+5gdkTxRkQ==,iv:Rn2aCKMtlwc66IxgdgJVaEjYH9MJwn55Nfw+JXpEEKk=,tag:pv0dKlKkcNjryppZZ/eUMw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wD7SYL+t+A==,iv:IimwZ2hB/Lltz3Svmpu7kBmum5B6OHbgmNyAx1ElADg=,tag:qcr6ROpn2bVJoC2A9Q6t/A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KDEXSo8fbJeJvq7EyN/Abhpn0RQfRgVKwT3ao2bQ2sT5b8roSmnIFQ==,iv:HuPN3t/CzaWPqwePktMV+XB4zSxqyEEmvmJHL9wD+EE=,tag:1BMkPJXIQ7W9bU0Rkal7QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scvdjv7h3s38cqtq4gsnj6cpsvh62zuhu8dy72uye4jksz2w39ds0skqm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDdPalAyYXl4dkJDQVNU
            ZjZzK0hVS2hKa2N6MWpMNk1XQncreUF6dFJFCm11NDRDNWNsQm5DVkw3STE1OGxn
            dWUyL1Z3SUxDSnIzMlAyeHR0SFJrZTAKLS0tIGlVa3JMRko2cEp2dGF4WEh1OEVw
            RFNNRDdSSmZWRFVxN3pEUnJabGRjV1EKzQpuuCcU/mf5ZBu3C7GrIz1J22Heewtv
            SazOJjV7CfsgVJmPMuK0womBacKciLD9emUTNqgJY/EqFxDYEkQUcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-05T05:37:17Z"
    mac: ENC[AES256_GCM,data:rbinXJpFn5EcROTfY8W0BXyXWPj+WXy53WfnIqqDWyJj5FAN8e1zhirtR0J+fpVIQ09+d96QucV2oki+7sJCnl7dx/vCi9cdTfO/fHmducR//AXi8bm2W2B4JQrin30Az8LEUKWTFirLXlhGPJQHEEabc/w5azf6WWTSVISRm9o=,iv:jpq56u0j2T3ZjuLF/tN6ee2TtgETkl/A/GGVUkdzFb8=,tag:nuDAkccOKbt04ixdu8SQPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
