log_level: info
schedule:
  interval: 1h
storage:
  path: /data
openwebui:
  base_url: "http://open-webui.ai.svc.cluster.local:8080"
github:
  enabled: true
  mappings:
    - repository: "binaryn3xus/HomeOps"
      knowledge_id: "5d24c9d4-75b2-4d90-bf5d-5f839303312d"