---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tuppr.home-operations.com/kubernetesupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  healthChecks:
    - apiVersion: volsync.backube/v1alpha1
      expr: |-
        status.conditions.filter(c, c.type == "Synchronizing").all(c, c.status == "False")
      kind: ReplicationSource
    - apiVersion: ceph.rook.io/v1
      expr: |-
        status.ceph.health in ['HEALTH_OK']
      kind: CephCluster
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.34.2
