---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vpn-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
      namespace: flux-system
  path: ./kubernetes/apps/vpn/vpn-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vpn-gateway
      namespace: vpn
  interval: 30m
  retryInterval: 1m
  timeout: 3m
