---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    external-dns.home.arpa/enabled: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  rules:
    - host: teleport.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teleport-cluster
                port:
                  number: 443
  tls:
    - hosts:
        - teleport.${SECRET_DOMAIN}
      secretName: teleport-tls
