---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: Default
resources:
  - helmrelease.yaml
  - config-pvc.yaml
  - secrets.sops.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: teleport
  app.kubernetes.io/instance: teleport
