---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-content-sync
spec:
  data:
    - remoteRef:
        key: OpenWebUi-Api-Key
      secretKey: openwebui_api_key
    - remoteRef:
        key: Github-PAT-OpenWebUI-Content-Sync
      secretKey: github_token
  refreshInterval: "12h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    creationPolicy: Owner
    name: openwebui-content-sync-secret
    template:
      data:
        GITHUB_TOKEN: "{{ .github_token }}"
        OPENWEBUI_API_KEY: "{{ .openwebui_api_key }}"
      engineVersion: v2
