---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.0.30.30"
  METALLB_LB_RANGE: "10.0.30.31-10.0.30.39"
  SVC_K8S_GATEWAY_ADDR: "10.0.30.31"
  SVC_INGRESS_ADDR: "10.0.30.32"
  SVC_PLEX_ADDR: "10.0.30.33"
  SVC_QBITTORRENT_ADDR: "10.0.30.34"
  SVC_TELEPORT_ADDR: "10.0.30.35"
  SVC_EMQX_ADDR: "10.0.30.36"
  SVC_HOME_ASSISTANT_ADDR: "10.0.30.37"
  HOME_NAS_IP: "10.0.30.4"
  LINK_SYNOLOGY_UI: "http://10.0.30.4/"
  LINK_MARK_SYNOLOGY: "https://thejollyroger.quickconnect.to/"
  LINK_MICHAEL_GITTEA: "https://gitea.torquasmvo.com/johndoe86x/"
