---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  CLUSTER_CLOUDFLARE_TUNNEL_ID: b9d1e81f-c1e0-4538-b153-bfe3cc327d2f
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.0.30.0/24"
  NGINX_EXTERNAL: "10.0.30.32"
  NGINX_INTERNAL: "10.0.30.33"
  SVC_PLEX_ADDR: "10.0.30.34"
  SVC_VECTOR_ADDR: "10.0.30.35"
  HOME_NAS_IP: "10.0.30.4"
