---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    app.kubernetes.io/instance: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    volsync.backube/privileged-movers: "true"
