---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app headlamp
spec:
  chartRef:
    kind: OCIRepository
    name: headlamp
  dependsOn: []
  install:
    remediation:
      retries: -1
  interval: 1h
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    clusterRoleBinding:
      create: false
    config:
      pluginsDir: /build/plugins
    env:
      - name: HEADLAMP_CONFIG_OIDC_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: headlamp-oidc-secret
            key: HEADLAMP_CONFIG_OIDC_CLIENT_ID
      - name: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: headlamp-oidc-secret
            key: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
      - name: HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL
        value: "https://github.com"
      - name: HEADLAMP_CONFIG_OIDC_SCOPES
        value: "openid,profile,email,read:org"
    fullnameOverride: headlamp
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.5.0@sha256:05c3df203b2ff82e09e944e31cd16ab66429f37df7566ba0d47285add7c78c5a
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      port: 80
      type: ClusterIP
    serviceAccount:
      create: false
      name: headlamp-admin
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - emptyDir: {}
        name: headlamp-plugins
