name: Update Minecraft Versions

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 UTC
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Update Minecraft Java version
        run: python scripts/update_minecraft_java_version.py

      - name: Update Minecraft Bedrock version
        run: python scripts/update_minecraft_bedrock_version.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update Minecraft Java and Bedrock VERSION in configmaps'
          title: 'chore: update Minecraft Java and Bedrock VERSION in configmaps'
          body: 'Automated PR to update the Minecraft Java and Bedrock VERSION in the configmaps to the latest releases.'
          branch: 'auto/update-minecraft-versions'
          delete-branch: true
