name: Update Minecraft Versions

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 UTC
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Update Minecraft Java version
        run: python scripts/update_minecraft_java_version.py

      - name: Update Minecraft Bedrock version
        run: python scripts/update_minecraft_bedrock_version.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          commit-message: 'chore: update Minecraft Java and Bedrock VERSION in configmaps'
          title: 'chore: update Minecraft Java and Bedrock VERSION in configmaps'
          body: 'Automated PR to update the Minecraft Java and Bedrock VERSION in the configmaps to the latest releases.'
          branch: 'auto/update-minecraft-versions'
          delete-branch: true
